name: prerender
description: "A Flutter widget for building layouts based on other widgets' dimensions."
version: 0.1.0
homepage: https://github.com/tomwyr/prerender

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
