name: Publish package to pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # tag-pattern on pub.dev: '{{version}}'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/publish_flutter_package
        # with:
        #   # Specify the github actions deployment environment
        #   working-directory: path/to/package/within/repository
